org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.226
loader_version_range=[1,)
sable_companion_version=1.4.2

mod_id=radios
mod_name=Useful Cross-Dimensional Radios
mod_license=MIT
mod_version=1.3.0
mod_group_id=ace.actually.radios
mod_authors=Acrogenous
mod_description=Actually useful radios with a minecrafty twist!
